<?php

/*
 * This file is part of the vinceamstoutz/symfony-security-auditor package.
 *
 * (c) Vincent Amstoutz <vincent.amstoutz.dev@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace VinceAmstoutz\SymfonySecurityAuditor\Audit\Infrastructure\Report;

use Override;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\AuditReport;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\Vulnerability;

/**
 * Renders an audit report as a pull-request comment body: the grade and
 * normalized score as a headline, then the most severe findings as one table
 * row each. Sized for a comment rather than a full report — {@see MARKER} lets
 * a workflow find its own previous comment and edit it in place, and the row cap
 * keeps a large report from hitting GitHub's comment length limit.
 *
 * @internal not part of the BC promise — see docs/versioning.md
 */
final readonly class GithubCommentReportRenderer implements ReportRendererInterface
{
    /**
     * An HTML comment, so it is invisible in the rendered body while still
     * greppable in the raw one.
     */
    public const string MARKER = '<!-- symfony-security-auditor:pr-comment -->';

    public const int MAX_ROWS = 10;

    #[Override]
    public function format(): string
    {
        return 'github-comment';
    }

    #[Override]
    public function render(AuditReport $auditReport): string
    {
        return implode("\n\n", [
            self::MARKER,
            $this->headline($auditReport),
            $this->runSummary($auditReport),
            ...$this->findings($auditReport),
            '---',
            $this->credit(),
        ]);
    }

    private function headline(AuditReport $auditReport): string
    {
        return \sprintf(
            '## Security audit: %s (%d/100)',
            $auditReport->grade()->value,
            $auditReport->normalizedScore(),
        );
    }

    private function runSummary(AuditReport $auditReport): string
    {
        return \sprintf(
            '**Risk level:** %s · **Findings:** %d · **Files scanned:** %d · **Duration:** %ss',
            $auditReport->riskLevel(),
            $auditReport->totalVulnerabilities(),
            $auditReport->filesScanned(),
            number_format($auditReport->durationSeconds(), 1, '.', ''),
        );
    }

    /**
     * @return list<string>
     */
    private function findings(AuditReport $auditReport): array
    {
        $vulnerabilities = $auditReport->vulnerabilities();
        if ([] === $vulnerabilities) {
            return ['✅ No validated vulnerabilities found.'];
        }

        $shown = \array_slice($vulnerabilities, 0, self::MAX_ROWS);

        return [
            $this->table($shown),
            ...$this->truncationNote(\count($shown), \count($vulnerabilities)),
        ];
    }

    /**
     * @param list<Vulnerability> $vulnerabilities
     */
    private function table(array $vulnerabilities): string
    {
        return implode("\n", [
            '| Severity | Finding | Location | Type |',
            '| --- | --- | --- | --- |',
            ...array_map($this->row(...), $vulnerabilities),
        ]);
    }

    private function row(Vulnerability $vulnerability): string
    {
        return \sprintf(
            '| %s | %s | %s | %s |',
            $vulnerability->severity()->label(),
            MarkdownTextEscaper::tableCell($vulnerability->title()),
            MarkdownTextEscaper::inlineCode(\sprintf('%s:%d', $vulnerability->filePath(), $vulnerability->lineStart())),
            MarkdownTextEscaper::inlineCode($vulnerability->type()->value),
        );
    }

    /**
     * @return list<string>
     */
    private function truncationNote(int $shown, int $total): array
    {
        if ($shown === $total) {
            return [];
        }

        return [\sprintf('_Showing the %d most severe of %d findings._', $shown, $total)];
    }

    private function credit(): string
    {
        return \sprintf('Generated by [%s](%s).', ReportPackage::NAME, ReportPackage::HOMEPAGE_URL);
    }
}
