<?php

/*
 * This file is part of the vinceamstoutz/symfony-security-auditor package.
 *
 * (c) Vincent Amstoutz <vincent.amstoutz.dev@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace VinceAmstoutz\SymfonySecurityAuditor\Audit\Infrastructure\Report;

use Override;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\AuditReport;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\Vulnerability;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilitySeverity;

/** @internal not part of the BC promise — see docs/versioning.md */
final readonly class MarkdownReportRenderer implements ReportRendererInterface
{
    #[Override]
    public function format(): string
    {
        return 'markdown';
    }

    #[Override]
    public function render(AuditReport $auditReport): string
    {
        $cost = $auditReport->cost();

        return implode("\n", [
            '# Security Audit Report',
            '',
            \sprintf(
                '**Audit ID:** %s · **Project:** %s · **Started:** %s · **Duration:** %ss',
                $auditReport->auditId(),
                $auditReport->projectPath(),
                $auditReport->startedAt()->format('Y-m-d H:i:s'),
                number_format($auditReport->durationSeconds(), 1, '.', ''),
            ),
            \sprintf(
                '**Tokens:** %s in / %s out · **Model:** %s · **Cost:** $%s (%s)',
                number_format($cost->inputTokens()),
                number_format($cost->outputTokens()),
                '' === $cost->primaryModel() ? 'unknown model' : $cost->primaryModel(),
                number_format($cost->estimatedCostUsd(), 4, '.', ''),
                $cost->hasPublishedPricing() ? 'published rates' : 'no published pricing, or a self-hosted model',
            ),
            '',
            \sprintf(
                '**Risk level:** %s (score %d) · **Findings:** %d · **Files scanned:** %d',
                $auditReport->riskLevel(),
                $auditReport->riskScore(),
                $auditReport->totalVulnerabilities(),
                $auditReport->filesScanned(),
            ),
            '',
            $this->body($auditReport),
            '',
            '---',
            '',
            \sprintf('Generated by [%s](%s).', ReportPackage::NAME, ReportPackage::HOMEPAGE_URL),
        ]);
    }

    private function body(AuditReport $auditReport): string
    {
        if (0 === $auditReport->totalVulnerabilities()) {
            return '✅ No validated vulnerabilities found.';
        }

        $lines = ['## Summary by severity', '', '| Severity | Count |', '| --- | --- |'];

        foreach (VulnerabilitySeverity::cases() as $severity) {
            $count = \count($auditReport->vulnerabilitiesBySeverity($severity));
            if ($count > 0) {
                $lines[] = \sprintf('| %s | %d |', $severity->label(), $count);
            }
        }

        $lines[] = '';
        $lines[] = \sprintf('## Findings (%d)', $auditReport->totalVulnerabilities());

        foreach ($auditReport->vulnerabilities() as $vulnerability) {
            $lines[] = '';
            $lines[] = $this->vulnerability($vulnerability);
        }

        return implode("\n", $lines);
    }

    private function vulnerability(Vulnerability $vulnerability): string
    {
        return implode("\n", [
            \sprintf('### %s — %s', $vulnerability->severity()->label(), MarkdownTextEscaper::heading($vulnerability->title())),
            '',
            \sprintf('- **Type:** `%s` (%s, %s)', $vulnerability->type()->value, $vulnerability->type()->owaspReference(), $vulnerability->type()->cwe()->label()),
            \sprintf('- **Location:** %s', MarkdownTextEscaper::inlineCode(\sprintf('%s:%d-%d', $vulnerability->filePath(), $vulnerability->lineStart(), $vulnerability->lineEnd()))),
            \sprintf('- **Confidence:** %s%%', \sprintf('%.0f', $vulnerability->confidence() * 100)),
            '',
            MarkdownTextEscaper::fences($vulnerability->description()),
            '',
            '**Vulnerable code:**',
            '',
            MarkdownTextEscaper::codeBlock($vulnerability->vulnerableCode()),
            '',
            \sprintf('**Attack vector:** %s', MarkdownTextEscaper::fences($vulnerability->attackVector())),
            '',
            '**Proof:**',
            '',
            MarkdownTextEscaper::codeBlock($vulnerability->proof()),
            '',
            ...$this->synthesizedPocLines($vulnerability),
            \sprintf('**Remediation:** %s', MarkdownTextEscaper::fences($vulnerability->remediation())),
            ...$this->suggestedFixLines($vulnerability),
        ]);
    }

    /**
     * @return list<string>
     */
    private function synthesizedPocLines(Vulnerability $vulnerability): array
    {
        $synthesizedPoC = $vulnerability->synthesizedPoC();
        if (null === $synthesizedPoC) {
            return [];
        }

        return ['**Synthesized PoC:**', '', MarkdownTextEscaper::codeBlock($synthesizedPoC), ''];
    }

    /**
     * @return list<string>
     */
    private function suggestedFixLines(Vulnerability $vulnerability): array
    {
        $suggestedFix = $vulnerability->suggestedFix();
        if (null === $suggestedFix) {
            return [];
        }

        return ['', '**Suggested fix:**', '', MarkdownTextEscaper::codeBlock($suggestedFix)];
    }
}
