<?php

/*
 * This file is part of the vinceamstoutz/symfony-security-auditor package.
 *
 * (c) Vincent Amstoutz <vincent.amstoutz.dev@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace VinceAmstoutz\SymfonySecurityAuditor\Audit\Infrastructure\Report;

use Override;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\AuditReport;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\Vulnerability;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilitySeverity;

/** @internal not part of the BC promise — see docs/versioning.md */
final readonly class MarkdownReportRenderer implements ReportRendererInterface
{
    #[Override]
    public function format(): string
    {
        return 'markdown';
    }

    #[Override]
    public function render(AuditReport $auditReport): string
    {
        $cost = $auditReport->cost();

        return implode("\n", [
            '# Security Audit Report',
            '',
            \sprintf(
                '**Audit ID:** %s · **Project:** %s · **Started:** %s · **Duration:** %ss',
                $auditReport->auditId(),
                $auditReport->projectPath(),
                $auditReport->startedAt()->format('Y-m-d H:i:s'),
                number_format($auditReport->durationSeconds(), 1, '.', ''),
            ),
            \sprintf(
                '**Tokens:** %s in / %s out · **Model:** %s',
                number_format($cost->inputTokens()),
                number_format($cost->outputTokens()),
                '' === $cost->primaryModel() ? 'unknown model' : $cost->primaryModel(),
            ),
            '',
            \sprintf(
                '**Risk level:** %s (score %d) · **Findings:** %d · **Files scanned:** %d',
                $auditReport->riskLevel(),
                $auditReport->riskScore(),
                $auditReport->totalVulnerabilities(),
                $auditReport->filesScanned(),
            ),
            '',
            $this->body($auditReport),
            '',
            '---',
            '',
            \sprintf('Generated by [%s](%s).', ReportPackage::NAME, ReportPackage::HOMEPAGE_URL),
        ]);
    }

    private function body(AuditReport $auditReport): string
    {
        if (0 === $auditReport->totalVulnerabilities()) {
            return '✅ No validated vulnerabilities found.';
        }

        $lines = ['## Summary by severity', '', '| Severity | Count |', '| --- | --- |'];

        foreach (VulnerabilitySeverity::cases() as $severity) {
            $count = \count($auditReport->vulnerabilitiesBySeverity($severity));
            if ($count > 0) {
                $lines[] = \sprintf('| %s | %d |', $severity->label(), $count);
            }
        }

        $lines[] = '';
        $lines[] = \sprintf('## Findings (%d)', $auditReport->totalVulnerabilities());

        foreach ($auditReport->vulnerabilities() as $vulnerability) {
            $lines[] = '';
            $lines[] = $this->vulnerability($vulnerability);
        }

        return implode("\n", $lines);
    }

    private function vulnerability(Vulnerability $vulnerability): string
    {
        return implode("\n", [
            \sprintf('### %s — %s', $vulnerability->severity()->label(), $this->escapeHeading($vulnerability->title())),
            '',
            \sprintf('- **Type:** `%s` (%s, %s)', $vulnerability->type()->value, $vulnerability->type()->owaspReference(), $vulnerability->type()->cwe()->label()),
            \sprintf('- **Location:** %s', $this->inlineCode(\sprintf('%s:%d-%d', $vulnerability->filePath(), $vulnerability->lineStart(), $vulnerability->lineEnd()))),
            \sprintf('- **Confidence:** %s%%', \sprintf('%.0f', $vulnerability->confidence() * 100)),
            '',
            $this->escapeFences($vulnerability->description()),
            '',
            '**Vulnerable code:**',
            '',
            $this->codeBlock($vulnerability->vulnerableCode()),
            '',
            \sprintf('**Attack vector:** %s', $this->escapeFences($vulnerability->attackVector())),
            '',
            '**Proof:**',
            '',
            $this->codeBlock($vulnerability->proof()),
            '',
            ...$this->synthesizedPocLines($vulnerability),
            \sprintf('**Remediation:** %s', $this->escapeFences($vulnerability->remediation())),
        ]);
    }

    /**
     * @return list<string>
     */
    private function synthesizedPocLines(Vulnerability $vulnerability): array
    {
        $synthesizedPoC = $vulnerability->synthesizedPoC();
        if (null === $synthesizedPoC) {
            return [];
        }

        return ['**Synthesized PoC:**', '', $this->codeBlock($synthesizedPoC), ''];
    }

    /**
     * LLM-produced narrative text is rendered as raw Markdown; an unescaped
     * run of backticks OR tildes (CommonMark allows either as a fence marker,
     * e.g. a ``` or ~~~ fence quoted mid-description) would open a code block
     * that only closes at the next such run — silently swallowing every
     * subsequent finding as inert code text once rendered. Backslash-escaping
     * each backtick/tilde keeps it a literal character instead. CommonMark
     * also passes raw inline HTML through verbatim, so `<`/`>` are entity-
     * encoded too — otherwise a payload like `<img onerror=...>` survives
     * into any downstream Markdown-to-HTML rendering of this report. `#` is
     * escaped too, since a description/attack-vector/remediation field is
     * legitimately multi-paragraph (unlike `title`, which is collapsed to one
     * line by {@see self::escapeHeading()}) and an embedded `\n\n## ` would
     * otherwise forge a fake top-level section heading mid-finding. A raw
     * backslash already present right before a backtick/tilde must be escaped
     * *first* — otherwise it combines with the backslash inserted below into
     * an escaped-backslash-then-live-marker sequence CommonMark still parses
     * as an open fence. `[`/`]` are escaped too: CommonMark's
     * `[display text](target)` link syntax needs no fence or heading marker
     * to work, so an unescaped title could forge a live, clickable link
     * straight into the rendered report.
     */
    private function escapeFences(string $text): string
    {
        $backslashesEscaped = str_replace('\\', '\\\\', mb_scrub($text, 'UTF-8'));

        return str_replace(['`', '~', '#', '<', '>', '[', ']'], ['\\`', '\\~', '\\#', '&lt;', '&gt;', '\\[', '\\]'], $backslashesEscaped);
    }

    /**
     * A finding's title is spliced directly into a single-line `###` heading,
     * with no surrounding code fence or paragraph break to contain it — an
     * embedded newline could forge a fake heading or horizontal rule as
     * unguarded top-level Markdown right where the title was expected.
     */
    private function escapeHeading(string $text): string
    {
        return $this->escapeFences(str_replace(["\r\n", "\r", "\n"], ' ', $text));
    }

    /**
     * Backslash escapes do not work inside a CommonMark code span — the
     * standard way to safely wrap arbitrary text in one is a delimiter longer
     * than any backtick run the text contains, padded with a leading space if
     * the text starts with a backtick (the only edge this is ever called with
     * — a location string always ends in a digit). `<`/`>` need no manual
     * entity encoding here: CommonMark renders code-span content as literal
     * text and HTML-escapes it automatically.
     */
    private function inlineCode(string $text): string
    {
        $text = mb_scrub($text, 'UTF-8');
        $delimiter = str_repeat('`', $this->longestBacktickRun($text) + 1);
        $padding = str_starts_with($text, '`') ? ' ' : '';

        return \sprintf('%s%s%s%s%s', $delimiter, $padding, $text, $padding, $delimiter);
    }

    private function longestBacktickRun(string $text): int
    {
        preg_match_all('/`+/', $text, $matches);

        return [] === $matches[0] ? 0 : max(array_map(\strlen(...), $matches[0]));
    }

    private function codeBlock(string $text): string
    {
        return implode("\n", array_map(
            static fn (string $line): string => \sprintf('    %s', $line),
            explode("\n", mb_scrub($text, 'UTF-8')),
        ));
    }
}
