services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: "8.3"
    environment:
      COMPOSER_ROOT_VERSION: "1.0.0"
    command: sleep infinity
    volumes:
      - .:/app
      - vendor:/app/vendor
      - composer-cache:/root/.composer/cache

volumes:
  vendor:
  composer-cache:
