<?php

/*
 * This file is part of the vinceamstoutz/symfony-security-auditor package.
 *
 * (c) Vincent Amstoutz <vincent.amstoutz.dev@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace VinceAmstoutz\SymfonySecurityAuditor\Tests\Unit\Infrastructure\Report;

use Override;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidAuditContextException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidAuditCostException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidCodeLocationException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidVulnerabilityClassificationException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidVulnerabilityNarrativeException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\AuditCost;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\CodeLocation;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\Vulnerability;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilityClassification;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilityNarrative;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilitySeverity;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilityType;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Infrastructure\Report\HtmlReportRenderer;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Infrastructure\Report\ReportRendererInterface;

final class HtmlReportRendererTest extends AbstractReportRendererTestCase
{
    #[Override]
    protected function createRenderer(): ReportRendererInterface
    {
        return new HtmlReportRenderer();
    }

    public function test_it_advertises_the_html_format(): void
    {
        self::assertSame('html', $this->renderer->format());
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_is_a_complete_document(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringContainsString('<!doctype html>', $output);
        self::assertStringContainsString('</html>', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_footer_links_to_the_project_homepage(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringContainsString(
            'Generated by <a href="https://github.com/vinceamstoutz/symfony-security-auditor">vinceamstoutz/symfony-security-auditor</a>.',
            $output,
        );
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_states_severity_counts_once_in_the_chart_not_twice(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(vulnerabilitySeverity: VulnerabilitySeverity::HIGH),
        ));

        self::assertStringNotContainsString('<table class="summary"', $output);
        self::assertStringNotContainsString('Summary by severity', $output);
        self::assertStringContainsString('aria-label="Findings by severity"', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_states_the_risk_of_an_audit_that_did_not_finish_as_covering_only_the_files_analyzed(): void
    {
        self::assertStringContainsString('<span class="risk risk-safe">SAFE</span> (score 0, on the files analyzed)', $this->renderer->render($this->makeIncompleteReport()));
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_states_no_risk_level_for_an_audit_that_analyzed_no_file(): void
    {
        $output = $this->renderer->render($this->makeReportThatAnalyzedNoFile());

        self::assertStringContainsString('<span class="risk risk-unknown">UNKNOWN</span> (no file was analyzed)', $output);
        self::assertStringNotContainsString('>SAFE<', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_gives_a_scan_that_found_no_file_no_verdict(): void
    {
        $output = $this->renderer->render($this->makeReportOfAScanThatFoundNoFile());

        self::assertStringContainsString('<span class="risk risk-unknown">UNKNOWN</span> (no file was analyzed)', $output);
        self::assertStringContainsString('<p class="incomplete">⚠️ Audit incomplete: the scan found no file to audit, so this report has no verdict', $output);
        self::assertStringNotContainsString('>SAFE<', $output);
        self::assertStringNotContainsString('No validated vulnerabilities found.', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_never_calls_an_incomplete_audit_clean(): void
    {
        self::assertStringNotContainsString('No validated vulnerabilities found.', $this->renderer->render($this->makeIncompleteReport()));
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_says_an_audit_without_findings_did_not_finish(): void
    {
        self::assertStringContainsString('<p class="incomplete">⚠️ Audit incomplete: 2 file(s)', $this->renderer->render($this->makeIncompleteReport()));
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_warns_even_when_the_incomplete_audit_found_something(): void
    {
        self::assertStringContainsString('<p class="incomplete">', $this->renderer->render($this->makeIncompleteReport($this->makeValidatedVuln())));
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_shows_safe_message_when_no_vulnerabilities(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringContainsString('No validated vulnerabilities found.', $output);
        self::assertStringNotContainsString('<h2>Vulnerabilities', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_renders_risk_level_with_its_lowercased_css_class(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringContainsString('class="risk risk-safe"', $output);
        self::assertStringContainsString('>SAFE</span>', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_shows_the_primary_model(): void
    {
        $output = $this->renderer->render($this->makeReportWithCost(AuditCost::zero('claude-test-model')));

        self::assertStringContainsString('claude-test-model', $output);
        self::assertStringNotContainsString('unknown model', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_shows_unknown_model_when_the_primary_model_is_blank(): void
    {
        $output = $this->renderer->render($this->makeReportWithCost(AuditCost::zero('')));

        self::assertStringContainsString('unknown model', $output);
    }

    /**
     * @throws InvalidAuditCostException
     * @throws InvalidAuditContextException
     */
    public function test_render_shows_the_cost_labeled_as_published_rates(): void
    {
        $output = $this->renderer->render($this->makeReportWithCost(AuditCost::of(100, 50, 0.0123, 'claude-opus-4-7')));

        self::assertStringContainsString('$0.0123 (published rates)', $output);
    }

    /**
     * @throws InvalidAuditCostException
     * @throws InvalidAuditContextException
     */
    public function test_render_caveats_zero_cost_when_tokens_were_spent_but_the_model_has_no_published_pricing(): void
    {
        $output = $this->renderer->render($this->makeReportWithCost(AuditCost::of(100, 50, 0.0, 'ollama/llama3.2')));

        self::assertStringContainsString('$0.0000 (no published pricing, or a self-hosted model)', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_lists_a_validated_vulnerability(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln(filePath: 'src/Admin/UserController.php')));

        self::assertStringContainsString('<h2>Vulnerabilities (1 total)</h2>', $output);
        self::assertStringContainsString('src/Admin/UserController.php', $output);
        self::assertStringContainsString('class="finding severity-high"', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_escapes_finding_content_to_prevent_report_xss(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::HIGH, '<script>alert(1)</script>', 0.9),
            new CodeLocation('src/Foo.php', 1, 2),
            new VulnerabilityNarrative('desc', 'vec', 'proof', 'fix'),
            'code',
        )->withReviewerValidation(true);

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringContainsString('&lt;script&gt;alert(1)&lt;/script&gt;', $output);
        self::assertStringNotContainsString('<script>alert(1)</script>', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_strips_unicode_bidi_override_characters_from_finding_content(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::HIGH, "Real\u{202E}txt.exe\u{202C} SQLi", 0.9),
            new CodeLocation('src/Foo.php', 1, 2),
            new VulnerabilityNarrative('desc', 'vec', 'proof', 'fix'),
            'code',
        )->withReviewerValidation(true);

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringContainsString('Real', $output);
        self::assertStringContainsString('txt.exe', $output);
        self::assertStringNotContainsString("\u{202E}", $output);
        self::assertStringNotContainsString("\u{202C}", $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_strips_terminal_control_sequences_from_finding_content(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::HIGH, "Title\x1b]0;pwned\x07 end", 0.9),
            new CodeLocation("src/\x1b[2JFoo.php", 1, 2),
            new VulnerabilityNarrative("desc\x1b[31m red\r overwritten\x00", "vec\u{85}tor", 'proof', 'fix'),
            "\$code\x7f",
        )->withReviewerValidation(true);

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertDoesNotMatchRegularExpression('/[\x{0}-\x{8}\x{B}-\x{1F}\x{7F}-\x{9F}]/u', $output);
        self::assertStringContainsString('Title]0;pwned end', $output);
        self::assertStringContainsString('src/[2JFoo.php:1-2', $output);
        self::assertStringContainsString('desc[31m red overwritten', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_keeps_the_line_breaks_and_tabs_of_a_code_snippet(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::HIGH, 'Title', 0.9),
            new CodeLocation('src/Foo.php', 1, 2),
            new VulnerabilityNarrative('desc', 'vec', 'proof', 'fix'),
            "if (\$a) {\n\treturn \$q;\n}",
        )->withReviewerValidation(true);

        self::assertStringContainsString("if (\$a) {\n\treturn \$q;\n}", $this->renderer->render($this->makeReport($vulnerability)));
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_strips_bidi_overrides_even_when_a_field_carries_invalid_utf8(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::HIGH, "\xFF\u{202E}evil", 0.9),
            new CodeLocation("src/\xFF\u{202E}cod.php", 1, 2),
            new VulnerabilityNarrative('desc', 'vec', 'proof', 'fix'),
            'code',
        )->withReviewerValidation(true);

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringNotContainsString("\u{202E}", $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_includes_the_vulnerable_code(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringContainsString('$q', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_includes_the_synthesized_poc_when_present(): void
    {
        $vulnerability = $this->makeValidatedVuln()->withSynthesizedPoC('curl -X POST https://victim.example/admin');
        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringContainsString('curl -X POST https://victim.example/admin', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_omits_the_synthesized_poc_section_when_absent(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringNotContainsString('Synthesized PoC', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_includes_the_suggested_fix_when_present(): void
    {
        $vulnerability = $this->makeValidatedVuln()->withSuggestedFix('--- a/src/A.php');
        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringContainsString('<h4>Suggested fix</h4>', $output);
        self::assertStringContainsString('--- a/src/A.php', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_omits_the_suggested_fix_section_when_absent(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringNotContainsString('Suggested fix', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_renders_confidence_as_a_percentage(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringContainsString('90%', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_formats_duration_with_a_period_regardless_of_the_process_numeric_locale(): void
    {
        $previousLocale = setlocale(\LC_NUMERIC, '0');
        setlocale(\LC_NUMERIC, 'de_DE.UTF-8');

        try {
            $auditReport = $this->makeReport();
            $output = $this->renderer->render($auditReport);
        } finally {
            setlocale(\LC_NUMERIC, false !== $previousLocale ? $previousLocale : 'C');
        }

        self::assertStringContainsString(number_format($auditReport->durationSeconds(), 1, '.', '').'s', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_replaces_every_template_placeholder(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringNotContainsString('{{', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_entity_encodes_single_quotes_via_ent_quotes(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringContainsString('&#039; OR 1=1', $output);
        self::assertStringNotContainsString("<pre>' OR 1=1", $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_renders_the_location_with_file_and_line_range(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(filePath: 'src/Repo.php', lineStart: 10),
        ));

        self::assertStringContainsString('<dd>src/Repo.php:10-14</dd>', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_lists_the_cwe_reference_alongside_owasp(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln(vulnerabilityType: VulnerabilityType::SQL_INJECTION)));

        self::assertStringContainsString('<dt>CWE</dt>', $output);
        self::assertStringContainsString('<dd>'.VulnerabilityType::SQL_INJECTION->cwe()->label().'</dd>', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_charts_the_severity_distribution(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(vulnerabilitySeverity: VulnerabilitySeverity::HIGH),
        ));

        self::assertStringContainsString(
            '<section class="charts"><h2>Distribution</h2><h3>By severity</h3><svg',
            $output,
        );
        self::assertStringContainsString('aria-label="Findings by severity"', $output);
        self::assertStringContainsString('class="bar bar-high"', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_charts_the_type_distribution(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(vulnerabilityType: VulnerabilityType::SQL_INJECTION),
        ));

        self::assertStringContainsString('aria-label="Findings by vulnerability type"', $output);
        self::assertStringContainsString('>'.VulnerabilityType::SQL_INJECTION->value.'</text>', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_charts_a_bar_for_every_present_severity(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(vulnerabilitySeverity: VulnerabilitySeverity::CRITICAL, filePath: 'src/One.php'),
            $this->makeValidatedVuln(vulnerabilitySeverity: VulnerabilitySeverity::LOW, filePath: 'src/Two.php'),
        ));

        self::assertStringContainsString('class="bar bar-critical"', $output);
        self::assertStringContainsString('class="bar bar-low"', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_charts_a_bar_for_every_present_vulnerability_type(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(vulnerabilityType: VulnerabilityType::SQL_INJECTION, filePath: 'src/One.php'),
            $this->makeValidatedVuln(vulnerabilityType: VulnerabilityType::TWIG_INJECTION, filePath: 'src/Two.php'),
        ));

        self::assertStringContainsString('>'.VulnerabilityType::SQL_INJECTION->value.'</text>', $output);
        self::assertStringContainsString('>'.VulnerabilityType::TWIG_INJECTION->value.'</text>', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_omits_the_charts_when_there_is_nothing_to_chart(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringNotContainsString('<svg', $output);
        self::assertStringNotContainsString('class="charts"', $output);
        self::assertStringNotContainsString('Distribution', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_charts_load_no_external_asset(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringNotContainsString('<script', $output);
        self::assertStringNotContainsString('<link', $output);
        self::assertStringNotContainsString('src=', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_styles_every_severity_bar_of_the_chart(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        foreach (VulnerabilitySeverity::cases() as $severity) {
            self::assertStringContainsString('svg.chart rect.bar-'.$severity->value, $output);
        }
    }
}
