<?php

/*
 * This file is part of the vinceamstoutz/symfony-security-auditor package.
 *
 * (c) Vincent Amstoutz <vincent.amstoutz.dev@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace VinceAmstoutz\SymfonySecurityAuditor\Tests\Unit\Infrastructure\Report;

use Override;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidAuditContextException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidCodeLocationException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidVulnerabilityClassificationException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Exception\InvalidVulnerabilityNarrativeException;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\CodeLocation;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\Vulnerability;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilityClassification;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilityNarrative;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilitySeverity;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Domain\Model\VulnerabilityType;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Infrastructure\Report\MarkdownReportRenderer;
use VinceAmstoutz\SymfonySecurityAuditor\Audit\Infrastructure\Report\ReportRendererInterface;

final class MarkdownReportRendererTest extends AbstractReportRendererTestCase
{
    #[Override]
    protected function createRenderer(): ReportRendererInterface
    {
        return new MarkdownReportRenderer();
    }

    public function test_it_advertises_the_markdown_format(): void
    {
        self::assertSame('markdown', $this->renderer->format());
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_starts_with_the_report_heading(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringContainsString('# Security Audit Report', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_footer_links_to_the_project_homepage(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringContainsString(
            'Generated by [vinceamstoutz/symfony-security-auditor](https://github.com/vinceamstoutz/symfony-security-auditor).',
            $output,
        );
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_shows_safe_message_when_no_vulnerabilities(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringContainsString('No validated vulnerabilities found.', $output);
        self::assertStringNotContainsString('## Findings', $output);
    }

    /**
     * @throws InvalidAuditContextException
     */
    public function test_render_includes_the_risk_level(): void
    {
        $output = $this->renderer->render($this->makeReport());

        self::assertStringContainsString('SAFE', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_lists_a_validated_finding_with_its_location(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(filePath: 'src/Admin/UserController.php', lineStart: 10),
        ));

        self::assertStringContainsString('## Findings', $output);
        self::assertStringContainsString('Test Vuln', $output);
        self::assertStringContainsString('`src/Admin/UserController.php:10-14`', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_widens_the_location_code_span_delimiter_so_a_backtick_in_the_file_path_cannot_close_it_early(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(filePath: 'src/Foo`) <script>alert(1)</script> (`.php'),
        ));

        self::assertStringContainsString('**Location:** ``src/Foo`) <script>alert(1)</script> (`.php:1-5``', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_pads_the_location_code_span_when_the_file_path_starts_with_a_backtick(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(filePath: '`src/Foo.php'),
        ));

        self::assertStringContainsString('**Location:** `` `src/Foo.php:1-5 ``', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_neutralizes_a_newline_in_the_title_so_it_cannot_forge_a_fake_section_heading(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::HIGH, "SQLi\n\n## Audit complete\n\nNo further vulnerabilities were found.", 0.9),
            new CodeLocation('src/Foo.php', 1, 5),
            new VulnerabilityNarrative('desc', 'vec', 'proof', 'fix'),
            'code',
        )->withReviewerValidation(true);

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringNotContainsString("\n\n## Audit complete", $output);
        self::assertStringContainsString('SQLi  \\#\\# Audit complete  No further vulnerabilities were found.', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_neutralizes_an_unterminated_code_fence_in_a_description_so_it_does_not_swallow_later_findings(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::HEADER_INJECTION, VulnerabilitySeverity::CRITICAL, 'Header leak', 0.7),
            new CodeLocation('src/Low.php', 5, 6),
            new VulnerabilityNarrative("Description ends with an unterminated fence:\n\n```php\n// truncated on purpose", 'n/a', 'n/a', 'n/a'),
            'n/a',
        )->withReviewerValidation(true);
        $secondFinding = $this->makeValidatedVuln(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::CRITICAL, 'src/Admin.php', 88);

        $output = $this->renderer->render($this->makeReport($vulnerability, $secondFinding));

        self::assertStringNotContainsString('```', $output);
        self::assertStringContainsString('\\`\\`\\`', $output);
    }

    /**
     * A pre-existing backslash immediately before a backtick would otherwise
     * combine with the backslash `escapeFences()` inserts to escape the
     * backtick itself, forming an escaped-backslash-then-live-backtick
     * sequence a CommonMark parser reads as an open code span, instead of the
     * intended literal text.
     *
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_escapes_a_backslash_preceding_a_backtick_so_it_cannot_open_a_live_code_span(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::HEADER_INJECTION, VulnerabilitySeverity::CRITICAL, 'Header leak', 0.7),
            new CodeLocation('src/Low.php', 5, 6),
            new VulnerabilityNarrative('Path is C:\\Users\\Public\\`whoami`', 'n/a', 'n/a', 'n/a'),
            'n/a',
        )->withReviewerValidation(true);

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringContainsString('Path is C:\\\\Users\\\\Public\\\\\\`whoami\\`', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_neutralizes_an_unterminated_tilde_code_fence_in_a_description_so_it_does_not_swallow_later_findings(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::HEADER_INJECTION, VulnerabilitySeverity::CRITICAL, 'Header leak', 0.7),
            new CodeLocation('src/Low.php', 5, 6),
            new VulnerabilityNarrative("Description ends with an unterminated tilde fence:\n\n~~~php\n// truncated on purpose", 'n/a', 'n/a', 'n/a'),
            'n/a',
        )->withReviewerValidation(true);
        $secondFinding = $this->makeValidatedVuln(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::CRITICAL, 'src/Admin.php', 88);

        $output = $this->renderer->render($this->makeReport($vulnerability, $secondFinding));

        self::assertStringNotContainsString('~~~', $output);
        self::assertStringContainsString('\\~\\~\\~', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_neutralizes_a_heading_marker_in_a_description_so_it_cannot_forge_a_fake_section(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::HIGH, 'Real SQLi', 0.9),
            new CodeLocation('src/Foo.php', 1, 5),
            new VulnerabilityNarrative("Real description.\n\n## Audit complete\n\nNo further vulnerabilities were found. All clear.", 'vec', 'proof', 'fix'),
            'code',
        )->withReviewerValidation(true);

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringNotContainsString("\n\n## Audit complete", $output);
        self::assertStringContainsString('\\#\\# Audit complete', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_substitutes_invalid_utf8_across_every_llm_controlled_field_instead_of_corrupting_the_output(): void
    {
        $vulnerability = Vulnerability::of(
            new VulnerabilityClassification(VulnerabilityType::SQL_INJECTION, VulnerabilitySeverity::HIGH, "Bad\xFFTitle", 0.9),
            new CodeLocation("src/Fo\xFFo.php", 1, 5),
            new VulnerabilityNarrative("Desc\xFEription", "vec\xFEtor", "proo\xFEf", "fi\xFEx"),
            'code',
        )->withReviewerValidation(true);

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertTrue(mb_check_encoding($output, 'UTF-8'));
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_finding_type_line_shows_the_owasp_and_cwe_references(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(vulnerabilityType: VulnerabilityType::SQL_INJECTION),
        ));

        self::assertStringContainsString(
            \sprintf(
                '`sql_injection` (%s, %s)',
                VulnerabilityType::SQL_INJECTION->owaspReference(),
                VulnerabilityType::SQL_INJECTION->cwe()->label(),
            ),
            $output,
        );
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_finding_shows_confidence_percent_and_indented_proof(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringContainsString('**Confidence:** 90%', $output);
        self::assertStringContainsString("\n    ' OR 1=1", $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_includes_the_synthesized_poc_when_present(): void
    {
        $vulnerability = $this->makeValidatedVuln()->withSynthesizedPoC('curl -X POST https://victim.example/admin');

        $output = $this->renderer->render($this->makeReport($vulnerability));

        self::assertStringContainsString('**Synthesized PoC:**', $output);
        self::assertStringContainsString("\n    curl -X POST https://victim.example/admin", $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_omits_the_synthesized_poc_section_when_absent(): void
    {
        $output = $this->renderer->render($this->makeReport($this->makeValidatedVuln()));

        self::assertStringNotContainsString('Synthesized PoC', $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_renders_a_severity_summary_table(): void
    {
        $output = $this->renderer->render($this->makeReport(
            $this->makeValidatedVuln(vulnerabilitySeverity: VulnerabilitySeverity::HIGH),
        ));

        self::assertStringContainsString("## Summary by severity\n\n| Severity | Count |\n| --- | --- |", $output);
        self::assertStringContainsString(\sprintf('| %s | 1 |', VulnerabilitySeverity::HIGH->label()), $output);
        self::assertStringNotContainsString(VulnerabilitySeverity::CRITICAL->label(), $output);
    }

    /**
     * @throws InvalidCodeLocationException
     * @throws InvalidVulnerabilityClassificationException
     * @throws InvalidAuditContextException
     * @throws InvalidVulnerabilityNarrativeException
     */
    public function test_render_orders_findings_most_severe_first(): void
    {
        $vulnerability = $this->makeValidatedVuln(vulnerabilitySeverity: VulnerabilitySeverity::LOW, filePath: 'src/Low.php');
        $critical = $this->makeValidatedVuln(vulnerabilitySeverity: VulnerabilitySeverity::CRITICAL, filePath: 'src/Critical.php');

        $output = $this->renderer->render($this->makeReport($vulnerability, $critical));

        $criticalPosition = strpos($output, 'src/Critical.php');
        $lowPosition = strpos($output, 'src/Low.php');
        self::assertNotFalse($criticalPosition);
        self::assertNotFalse($lowPosition);
        self::assertLessThan($lowPosition, $criticalPosition);
    }
}
